# -*- coding: utf-8 -*-
"""25coco_training_model_v8l.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SLJQA9a87wsYc9kRg3OzGwLz8wAYs_GU

# YOLOv8l Training on 25 COCO Classes (Colab Ready)
This notebook:
- Prepares a **25-class subset** of COCO.
- Auto-fixes empty validation set (reuses some train images).
- Trains **YOLOv8l** for **100 epoch**.
- Produces **confusion matrix** and **metrics**.
- Extracts YOLOv8 metrics (Precision, Recall, mAP50, mAP50-95) and plots them.
"""

# ==============================
# 1) Setup
# ==============================
# !pip install -q ultralytics==8.3.2 matplotlib pandas pyyaml

import os, glob, shutil, yaml
from pathlib import Path

# Force reinstall a compatible numpy
!pip install --force-reinstall numpy==1.26.4

!mkdir -p /content/coco


!wget -nc http://images.cocodataset.org/zips/train2017.zip -P /content/coco


!wget -nc http://images.cocodataset.org/zips/val2017.zip -P /content/coco


!wget -nc http://images.cocodataset.org/zips/test2017.zip -P /content/coco


!wget -nc http://images.cocodataset.org/annotations/annotations_trainval2017.zip -P /content/coco


!unzip -q /content/coco/train2017.zip -d /content/coco/
!unzip -q /content/coco/val2017.zip -d /content/coco/
!unzip -q /content/coco/test2017.zip -d /content/coco/
!unzip -q /content/coco/annotations_trainval2017.zip -d /content/coco/

print("✅ COCO 2017 dataset ready at /content/coco")

# COCO names
COCO_NAMES = [
    'person','bicycle','car','motorcycle','airplane','bus','train','truck','boat','traffic light',
    'fire hydrant','stop sign','parking meter','bench','bird','cat','dog','horse','sheep','cow',
    'elephant','bear','zebra','giraffe','backpack','umbrella','handbag','tie','suitcase','frisbee',
    'skis','snowboard','sports ball','kite','baseball bat','baseball glove','skateboard','surfboard','tennis racket','bottle',
    'wine glass','cup','fork','knife','spoon','bowl','banana','apple','sandwich','orange',
    'broccoli','carrot','hot dog','pizza','donut','cake','chair','couch','potted plant','bed',
    'dining table','toilet','tv','laptop','mouse','remote','keyboard','cell phone','microwave','oven',
    'toaster','sink','refrigerator','book','clock','vase','scissors','teddy bear','hair drier','toothbrush'
]

# Pick 25
SELECTED_25 = [
    'person','bicycle','car','motorcycle','bus','truck','traffic light','stop sign','bench','dog',
    'cat','horse','sheep','cow','bird','bottle','cup','fork','knife','spoon',
    'bowl','banana','apple','chair','tv'
]
SELECTED_25_IDX = [COCO_NAMES.index(n) for n in SELECTED_25]

from ultralytics.utils.downloads import download

root = Path('datasets')
root.mkdir(parents=True, exist_ok=True)
download('https://ultralytics.com/assets/coco128.zip', dir=root, unzip=True, delete=True)
print("✅ COCO128 downloaded")

SRC = 'datasets/coco128'
DST = 'datasets/coco128_25'
for sub in ['images/train2017','images/val2017','labels/train2017','labels/val2017']:
    os.makedirs(os.path.join(DST, sub), exist_ok=True)

def filter_split(split):
    import os
    kept = 0
    for lbl_path in glob.glob(os.path.join(SRC, f'labels/{split}/*.txt')):
        base = os.path.splitext(os.path.basename(lbl_path))[0]
        img_path = os.path.join(SRC, f'images/{split}/{base}.jpg')
        if not os.path.exists(img_path):
            continue
        # filter
        with open(lbl_path, 'r') as f:
            lines = f.read().strip().splitlines()
        new_lines = []
        for line in lines:
            parts = line.split()
            if not parts: continue
            cls_id = int(parts[0])
            if cls_id in SELECTED_25_IDX:
                remap = SELECTED_25_IDX.index(cls_id)
                parts[0] = str(remap)
                new_lines.append(' '.join(parts))
        if new_lines:
            shutil.copy2(img_path, f"{DST}/images/{split}/{os.path.basename(img_path)}")
            with open(f"{DST}/labels/{split}/{os.path.basename(lbl_path)}","w") as w:
                w.write("\n".join(new_lines))
            kept += 1
    print(f"{split}: kept {kept}")

filter_split('train2017')
filter_split('val2017')

yaml_path = f"{DST}/coco128_25.yaml"

# Ensure val not empty
val_imgs = glob.glob(f"{DST}/images/val2017/*.jpg")
if len(val_imgs) == 0:
    print("⚠️ No val images found, reusing train set for val")
    os.makedirs(f"{DST}/images/val2017", exist_ok=True)
    os.makedirs(f"{DST}/labels/val2017", exist_ok=True)
    for img in glob.glob(f"{DST}/images/train2017/*.jpg")[:20]:
        base = os.path.basename(img)
        lbl = img.replace("images","labels").replace(".jpg",".txt")
        shutil.copy(img, f"{DST}/images/val2017/{base}")
        if os.path.exists(lbl):
            shutil.copy(lbl, f"{DST}/labels/val2017/{os.path.basename(lbl)}")

# Write yaml
data_yaml = {
    "path": str(Path(DST).absolute()),
    "train": "images/train2017",
    "val": "images/val2017",
    "nc": len(SELECTED_25),
    "names": SELECTED_25
}
with open(yaml_path, "w") as f:
    yaml.safe_dump(data_yaml, f, sort_keys=False)
print("✅ Wrote dataset yaml:", yaml_path)

!pip uninstall -y wandb

from ultralytics import YOLO
import os
os.environ["WANDB_MODE"] = "disabled"  # disable wandb logging

y8 = YOLO('yolov8l.pt')
results = y8.train(
    data='datasets/coco128_25/coco128_25.yaml',
    epochs=100,
    imgsz=640,
    batch=-1,
    device=0,
    workers=2,
    pretrained=True,
    amp=True,
    seed=0,
    project='runs_yolo8',
    name='yolov8l_25coco_1e'
)

val_res = y8.val(
    project='runs_yolo8',
    name='yolov8l_25coco_val',
    plots=True
)
print("Validation metrics:", val_res.results_dict)

import pandas as pd, matplotlib.pyplot as plt, json

y8_val_dir = 'runs_yolo8/yolov8l_25coco_val'
metrics_file = Path(y8_val_dir) / 'results.json'

metrics = {}
if metrics_file.exists():
    with open(metrics_file,'r') as f:
        metrics = json.load(f)

row = {
    "Model":"YOLOv8l",
    "mAP50-95": metrics.get("metrics/mAP50-95(B)") or metrics.get("mAP50-95"),
    "mAP50": metrics.get("metrics/mAP50(B)") or metrics.get("mAP50"),
    "Precision": metrics.get("metrics/precision(B)") or metrics.get("precision"),
    "Recall": metrics.get("metrics/recall(B)") or metrics.get("recall")
}

df = pd.DataFrame([row])
display(df)

vals = [row["mAP50-95"], row["mAP50"], row["Precision"], row["Recall"]]
if all(v is not None for v in vals):
    plt.figure(figsize=(6,4))
    plt.bar(["mAP50-95","mAP50","Precision","Recall"], vals)
    plt.title("YOLOv8l Metrics (1 Epoch, 25 COCO Classes)")
    plt.ylabel("Score")
    plt.show()
else:
    print("⚠️ Metrics not available, check val set or increase epochs.")

import pandas as pd
import matplotlib.pyplot as plt

# Assuming results.csv exists in your YOLO run folder
df = pd.read_csv("runs_yolo8/yolov8l_25coco_1e/results.csv")
plt.plot(df["epoch"], df["train/box_loss"], label="Box Loss")
plt.plot(df["epoch"], df["train/cls_loss"], label="Class Loss")
plt.plot(df["epoch"], df["train/dfl_loss"], label="DFL Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.title("Training Losses")
plt.show()

